# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/126hX7FQUmEJurImSrhqUf_F2FOoOrkLQ
"""

print("Programa que calcule la area de un triangulo  ")
a=int(input("Ingresar la altura del triangulo "))
b=int(input("Ingresar la base del triangulo  "))
A=(a+b)/2
print("la area del triangulo es:  ")
print(A)